r1_mecanum_node:
  # ros__parameters:
  #   # 50mm
  #   wheel_radius: 0.05
  #   # 586.6mm
  #   robot_length: 0.5886
  #   # 604mm
  #   robot_width: 0.604
  #   speed_limit: 30.0
  #   # モーターの出力は歯数が34（モーター側）と歯数が42（ホイール側）で組みあわせているので
  #   # 減速比は34 / 42 = 0.8095238095238095
  #   # ギア比で割った値がモーターの出力となる
  #   gear_ratio: 0.8095238095238095
  #   motor_inverse: [false, false, true, true]
  ros__parameters:
    # 37.5mm
    wheel_radius: 0.0375
    # 0.450mm
    robot_length: 0.450
    # 661mm
    robot_width: 0.661
    speed_limit: 75.0
    # モーターの出力は歯数が37（モーター側）と歯数が28（ホイール側）で組みあわせているので
    # 減速比は37 / 28 = 1.3214285714285714
    # ギア比で割った値がモーターの出力となる
    gear_ratio: 1.3214285714285714
    motor_inverse: [true, true, false, false]
    use_imu: false
r1_odometry_node:
  ros__parameters:
    # 計測輪の半径[m]
    # 使ったオムニは小さい白オムニ
    # 適当に実測したパラメータなので、ずれてるかも
    wheel_radius: 0.025
    encoder_x_inverse: false
    encoder_y_inverse: true
    use_imu: false

r1_sabacan_msgs_converter_node:
  ros__parameters:
    # メカナム
    mecanum_fl_board_id: 1
    mecanum_fr_board_id: 1
    mecanum_rl_board_id: 1
    mecanum_rr_board_id: 1
    mecanum_fl_motor_number: 0
    mecanum_fr_motor_number: 1
    mecanum_rl_motor_number: 2
    mecanum_rr_motor_number: 3
    # オドメトリ用エンコーダ、メカナムの基板と兼用
    odometry_x_board_id: 1
    odometry_y_board_id: 1
    odometry_x_motor_number: 2
    odometry_y_motor_number: 3
    # リニアモーション（ロボマス）
    linear_motion_board_id: 2
    linear_motion_motor_number: 0
    # リミットスイッチ（GPIO入力）
    linear_motion_low_switch_board_id: 1
    linear_motion_low_switch_gpio_number: 0
    linear_motion_high_switch_board_id: 1
    linear_motion_high_switch_gpio_number: 1

r1_linear_motion_node:
  ros__parameters:
    use_low_switch: true
    use_high_switch: true
    pos_min: 0.0
    pos_max: 1.0
    pos_offset: 0.0
    inverse_motor: false

sabacan_gpio_node1:
  ros__parameters:
    board_id: 1
    pin_type: ["INPUT", "INPUT", "INPUT", "INPUT", "INPUT", "INPUT", "INPUT", "INPUT", "INPUT"]

sabacan_robomas_node1:
  ros__parameters:
    board_id: 1
    motor_type: ["C620", "C620", "C620", "C620"]
    control_type: ["VELOCITY", "VELOCITY", "VELOCITY", "VELOCITY"]
    speed_gain_p: [0.5, 0.5, 0.5, 0.5]
    speed_gain_i: [0.2, 0.2, 0.2, 0.2]
    speed_gain_d: [0.0, 0.0, 0.0, 0.0]
    pos_gain_p: [6.0, 6.0, 6.0, 6.0]
    pos_gain_i: [3.0, 3.0, 3.0, 3.0]
    pos_gain_d: [0.0, 0.0, 0.0, 0.0]
    speed_lim: [75.0, 75.0, 75.0, 75.0]
    # VESCのフィードバックは無効化
    monitor_reg2: [0, 0, 0, 0]
sabacan_robomas_node2:
  ros__parameters:
    board_id: 2
    motor_type: ["C610", "C610", "C610", "C610"]
    control_type: ["POS", "POS", "POS", "POS"]
    speed_gain_p: [0.5, 0.5, 0.5, 0.5]
    speed_gain_i: [0.2, 0.2, 0.2, 0.2]
    speed_gain_d: [0.0, 0.0, 0.0, 0.0]
    pos_gain_p: [6.0, 6.0, 6.0, 6.0]
    pos_gain_i: [3.0, 3.0, 3.0, 3.0]
    pos_gain_d: [0.0, 0.0, 0.0, 0.0]
    speed_lim: [75.0, 75.0, 75.0, 75.0]
    # VESCのフィードバックは無効化
    monitor_reg2: [0, 0, 0, 0]
