r1_main_node:
  ros__parameters:
    # ========== 足回り ==========
    chassis_max_velocity: 1.0
    chassis_max_omega: 1.57

    # ========== KFS回収 ==========
    # fx
    kfs_fx_normal_pos: 0.05
    kfs_fx_expand_pos: 0.5
    # fz
    kfs_fz_normal_pos: 0.02
    kfs_fz_low_pos: 0.02
    kfs_fz_middle_pos: 0.22
    kfs_fz_high_pos: 0.42
    kfs_fz_book_pos: 0.52
    # fyaw
    kfs_fyaw_normal_angle: 0.0
    kfs_fyaw_front_angle: 0.0
    kfs_fyaw_side_angle: 1.57
    kfs_fyaw_rear_angle: 3.14
    # rx
    kfs_rx_normal_pos: 0.05
    kfs_rx_expand_pos: 0.5
    # rz
    kfs_rz_normal_pos: 0.02
    kfs_rz_low_pos: 0.02
    kfs_rz_middle_pos: 0.22
    kfs_rz_high_pos: 0.42
    kfs_rz_book_pos: 0.52
    # ryaw
    kfs_ryaw_normal_angle: 0.0
    kfs_ryaw_front_angle: 0.0
    kfs_ryaw_side_angle: 1.57
    kfs_ryaw_rear_angle: 3.14

    # ========== 展開 ==========
    # R2昇降
    r2_lift_max_velocity: 15.0
    # front_expand
    front_expand_normal_pos: 0.0
    front_expand_expand_pos: 0.5
    # rear_expand
    rear_expand_normal_pos: 0.0
    rear_expand_expand_pos: 0.5

    # ========== ポール回収 ==========
    # pole_x1
    pole_x1_normal_pos: 0.275
    pole_x1_expand_pos: 0.0
    # pole_x2
    pole_x2_normal_pos: 0.275
    pole_x2_expand_pos: 0.0
    # pole_y
    pole_y_normal_pos: 0.0
    pole_y_collect_pos: 0.0
    pole_y_transfer1_pos: 0.10
    pole_y_transfer2_pos: 0.27
    pole_y_transfer3_pos: 0.0
    pole_y_transfer4_pos: 0.4
    # pole_roger
    pole_roger_normal_pos: 0.0
    pole_roger_expand_pos: 0.5
    # pole servo
    # servo1
    pole_servo1_normal_angle: 70
    pole_servo1_horizontal_angle: 186
    # servo2
    pole_servo2_normal_angle: 80
    pole_servo2_horizontal_angle: 180
    # servo3
    pole_servo3_normal_angle: 70
    pole_servo3_horizontal_angle: 180
    # servo4
    pole_servo4_normal_angle: 70
    pole_servo4_horizontal_angle: 185

    # ========== やり ==========
    # roger1
    spear_roger1_normal_pos: 0.0
    spear_roger1_combine_pos: 0.0
    spear_roger1_transfer_pos: 0.38
    # roger2
    spear_roger2_normal_pos: 0.0
    spear_roger2_combine_pos: 0.0
    # うまく動かないので、roger1より高くする
    spear_roger2_transfer_pos: 0.38
    # move
    spear_move_normal_pos: 0.0
    spear_move_combine_pos: 0.0
    spear_move_transfer_pos: 0.45
    # TODO: ここの名前わかりにくいので治す
    spear_move_valve1_pos: 0.0
    spear_move_valve2_pos: 0.2
    # rotate
    spear_rotate_normal_pos: 0.0
    spear_rotate_combine_angle: 3.3


# -------- 足回り ----------
r1_mecanum_node:
  ros__parameters:
  #   # 50mm
    wheel_radius: 0.05
  #   # 470mm
    robot_length: 0.470
  #   # 484mm
    robot_width: 0.484
    speed_limit: 75.0
  #   # モーターの出力は歯数が34（モーター側）と歯数が42（ホイール側）で組みあわせているので
  # モーターの出力は歯数が32（モーター側）と歯数が64（ホイール側）で組みあわせているので
  #   # 減速比は32 / 64 = 0.5
  #   # ギア比で割った値がモーターの出力となる
    gear_ratio: 0.5
    motor_inverse: [true, false, false, true]
    use_imu: true
r1_odometry_node:
  ros__parameters:
    # 計測輪の半径[m]
    # 使ったオムニは小さい白オムニ
    # 適当に実測したパラメータなので、ずれてるかも
    wheel_radius: 0.025
    encoder_x_inverse: false
    encoder_y_inverse: true
    use_imu: false

# ---------- KFS回収機構 ----------
# linear motion node
r1_kfs_fx_node:
  ros__parameters:
    torque_threshold: 0.5 # Nm
    origin_detect_threshold_time: 0.5 # 秒
    # 原点検出のときは、0の方向に戻るので、負の速度にする
    output_detect_speed: -6.28 # rad/s
    pos_min: 0.0
    pos_max: 1.0
    normal_pos: 0.05
    # ギアが一周すると2*pi*15mm進むので、半径は15mm
    radius: 0.015
    inverse_motor: true
    use_low_switch: false
    use_high_switch: false
    inverse_low_switch_logic: false
    inverse_high_switch_logic: false
# linear motion node
r1_kfs_fz_node:
  ros__parameters:
    torque_threshold: 0.5 # Nm
    origin_detect_threshold_time: 0.5 # 秒
    # 原点検出のときは、0の方向に戻るので、負の速度にする
    output_detect_speed: -3.14 # rad/s
    pos_min: 0.0
    pos_max: 1.0
    normal_pos: 0.05
    # ギアが一周すると2*pi*15mm進むので、半径は15mm
    radius: 0.015
    inverse_motor: true
    use_low_switch: false
    use_high_switch: false
    inverse_low_switch_logic: false
    inverse_high_switch_logic: false
# angle motion node
r1_kfs_fyaw_node:
  ros__parameters:
    # torque_threshold: 0.5 # Nm
    torque_threshold: 0.2 # Nm
    origin_detect_threshold_time: 0.5 # 秒
    origin_detect_speed: -3.14 # rad/s
    angle_min: -5.0
    angle_max: 5.0
    normal_angle: 0.0
    # ギア比で割った値がモーターの角度指令値となる
    # 減速比は26 / 80 = 0.325
    gear_ratio: 0.325
    inverse_motor: false
    use_low_switch: false
    use_high_switch: false
    inverse_low_switch_logic: false
    inverse_high_switch_logic: false
# linear motion node
r1_kfs_rx_node:
  ros__parameters:
    torque_threshold: 0.5 # Nm
    origin_detect_threshold_time: 0.5 # 秒
    # 原点検出のときは、0の方向に戻るので、負の速度にする
    output_detect_speed: -3.14 # rad/s
    pos_min: 0.0
    pos_max: 1.0
    normal_pos: 0.05
    # ギアが一周すると2*pi*15mm進むので、半径は15mm
    radius: 0.015
    inverse_motor: false
    use_low_switch: false
    use_high_switch: false
    inverse_low_switch_logic: false
    inverse_high_switch_logic: false
# linear motion node
r1_kfs_rz_node:
  ros__parameters:
    torque_threshold: 0.5 # Nm
    origin_detect_threshold_time: 0.5 # 秒
    # 原点検出のときは、0の方向に戻るので、負の速度にする
    output_detect_speed: -3.14 # rad/s
    pos_min: 0.0
    pos_max: 1.0
    normal_pos: 0.05
    # ギアが一周すると2*pi*15mm進むので、半径は15mm
    radius: 0.015
    inverse_motor: false
    use_low_switch: false
    use_high_switch: false
    inverse_low_switch_logic: false
    inverse_high_switch_logic: false
# angle motion node
r1_kfs_ryaw_node:
  ros__parameters:
    # torque_threshold: 0.5 # Nm
    torque_threshold: 0.2 # Nm
    origin_detect_threshold_time: 0.5 # 秒
    origin_detect_speed: -3.14 # rad/s
    angle_min: -5.0
    angle_max: 5.0
    normal_angle: 0.0
    # ギア比で割った値がモーターの角度指令値となる
    # 減速比は26 / 80 = 0.325
    gear_ratio: 0.325
    inverse_motor: true
    use_low_switch: false
    use_high_switch: false
    inverse_low_switch_logic: false
    inverse_high_switch_logic: false
# ---------- 展開 ----------
# linear motion node
r1_front_expand_node:
  ros__parameters:
    torque_threshold: 0.5 # Nm
    origin_detect_threshold_time: 0.5 # 秒
    # 原点検出のときは、0の方向に戻るので、負の速度にする
    output_detect_speed: -3.14 # rad/s
    pos_min: 0.0
    pos_max: 1.0
    normal_pos: 0.05
    # ギアが一周すると2*pi*26mm進むので、半径は26mm
    radius: 0.026
    inverse_motor: false
    use_low_switch: false
    use_high_switch: false
    inverse_low_switch_logic: false
    inverse_high_switch_logic: false
# linear motion node
r1_rear_expand_node:
  ros__parameters:
    torque_threshold: 0.5 # Nm
    origin_detect_threshold_time: 0.5 # 秒
    # 原点検出のときは、0の方向に戻るので、負の速度にする
    output_detect_speed: -3.14 # rad/s
    pos_min: 0.0
    pos_max: 1.0
    normal_pos: 0.05
    # ギアが一周すると2*pi*26mm進むので、半径は26mm
    radius: 0.026
    inverse_motor: false
    use_low_switch: false
    use_high_switch: false
    inverse_low_switch_logic: false
    inverse_high_switch_logic: false

# ---------- ポール回収 ----------
# linear motion node
r1_pole_x1_node:
  ros__parameters:
    torque_threshold: 0.5 # Nm
    origin_detect_threshold_time: 0.5 # 秒
    # 原点検出のときは、0の方向に戻るので、負の速度にする
    output_detect_speed: -3.14 # rad/s
    pos_min: 0.0
    pos_max: 1.0
    normal_pos: 0.05
    # ギアが一周すると2*pi*20mm進むので、半径は20mm
    radius: 0.02
    inverse_motor: false
    use_low_switch: false
    use_high_switch: false
    inverse_low_switch_logic: false
    inverse_high_switch_logic: false
r1_pole_x2_node:
  ros__parameters:
    torque_threshold: 0.5 # Nm
    origin_detect_threshold_time: 0.5 # 秒
    # 原点検出のときは、0の方向に戻るので、負の速度にする
    output_detect_speed: -3.14 # rad/s
    pos_min: 0.0
    pos_max: 1.0
    normal_pos: 0.05
    # ギアが一周すると2*pi*20mm進むので、半径は20mm
    radius: 0.02
    inverse_motor: true
    use_low_switch: false
    use_high_switch: false
    inverse_low_switch_logic: false
    inverse_high_switch_logic: false
# linear motion node
r1_pole_y_node:
  ros__parameters:
    torque_threshold: 0.5 # Nm
    origin_detect_threshold_time: 0.5 # 秒
    # 原点検出のときは、0の方向に戻るので、負の速度にする
    output_detect_speed: -3.14 # rad/s
    pos_min: 0.0
    pos_max: 1.0
    normal_pos: 0.05
    # ギアが一周すると2*pi*20mm進むので、半径は20mm
    radius: 0.02
    inverse_motor: true
    use_low_switch: false
    use_high_switch: false
    inverse_low_switch_logic: false
    inverse_high_switch_logic: false
# linear motion node
r1_pole_roger_node:
  ros__parameters:
    torque_threshold: 0.5 # Nm
    origin_detect_threshold_time: 0.5 # 秒
    # 原点検出のときは、0の方向に戻るので、負の速度にする
    output_detect_speed: -3.14 # rad/s
    pos_min: 0.0
    pos_max: 1.0
    normal_pos: 0.05
    # 1回転すると70mm進む。ロジャーなので、倍進むので、半径0.05570423mm
    radius: 0.05570423
    inverse_motor: true
    use_low_switch: false
    use_high_switch: false
    inverse_low_switch_logic: false
    inverse_high_switch_logic: false
# ---------- やり ----------
# linear motion node
r1_spear_roger1_node:
  ros__parameters:
    torque_threshold: 0.5 # Nm
    origin_detect_threshold_time: 0.5 # 秒
    # 原点検出のときは、0の方向に戻るので、負の速度にする
    output_detect_speed: -3.14 # rad/s
    pos_min: -0.1
    pos_max: 1.0
    normal_pos: 0.05
    # 1回転すると70mm進む。ロジャーなので、倍進むので、半径0.05570423mm
    radius: 0.05570423
    inverse_motor: true
    use_low_switch: false
    use_high_switch: false
    inverse_low_switch_logic: false
    inverse_high_switch_logic: false
# linear motion node
r1_spear_roger2_node:
  ros__parameters:
    torque_threshold: 0.5 # Nm
    origin_detect_threshold_time: 0.5 # 秒
    # 原点検出のときは、0の方向に戻るので、負の速度にする
    output_detect_speed: -3.14 # rad/s
    pos_min: -0.1
    pos_max: 1.0
    normal_pos: 0.05
    # 1回転すると70mm進む。ロジャーなので、倍進むので、半径0.05570423mm
    radius: 0.05570423
    inverse_motor: true
    use_low_switch: false
    use_high_switch: false
    inverse_low_switch_logic: false
    inverse_high_switch_logic: false
# linear motion node
r1_spear_move_node:
  ros__parameters:
    # torque_threshold: 0.5 # Nm
    origin_detect_threshold_time: 0.2 # 秒
    # 原点検出のときは、0の方向に戻るので、負の速度にする
    output_detect_speed: -3.14 # rad/s
    pos_min: -0.1
    pos_max: 1.0
    normal_pos: 0.05
    # 1回転すると95mm進むので、半径は15.119719mm
    radius: 0.015119719
    inverse_motor: false
    use_low_switch: true
    use_high_switch: false
    inverse_low_switch_logic: false
    inverse_high_switch_logic: false
# angle motion node
r1_spear_rotate_node:
  ros__parameters:
    # torque_threshold: 0.5 # Nm
    origin_detect_threshold_time: 0.4 # 秒
    origin_detect_speed: -3.14 # rad/s
    angle_min: -1.0
    angle_max: 5.0
    normal_angle: 0.0
    # ギア比は1.0
    gear_ratio: 1.0
    inverse_motor: false
    use_low_switch: true
    use_high_switch: false
    inverse_low_switch_logic: false
    inverse_high_switch_logic: false

# IMU
bno086_node:
  ros__parameters:
    port: "/dev/ttyUSB0"

# 足回り
sabacan_robomasv2_node_id1:
  ros__parameters:
    board_id: 1
    enable_initialize: false
    motor_type: ["VESC", "VESC", "VESC", "VESC"]
    control_type: ["VELOCITY", "VELOCITY", "VELOCITY", "VELOCITY"]
    # モータ番号0と1はABS_SPD,ABS_POSをフィードバック
    # モータ番号2と3はフィードバックなし
    monitor_reg1: [0x0C00000000000000, 0x0C00000000000000, 0x0, 0x0]
    # モータ番号0と1はMOTOR_STATE,ABS_SPD,ABS_POSをフィードバック
    # モータ番号2と3はMOTOR_STATEのみフィードバック
    # monitor_reg1: [0x0C00000000000002, 0x0C00000000000002, 0x2, 0x2]
    # VESC_CURRENT + VESC_ERPMをフィードバック
    monitor_reg2: [0x18, 0x18, 0x18, 0x18]
    monitor_period: 20

# KFS回収前、展開補助前
sabacan_robomasv2_node_id2:
  ros__parameters:
    board_id: 2
    enable_initialize: false
    motor_type: ["C610", "C610", "C610", "C610"]
    control_type: ["POS", "POS", "POS", "POS"]
    speed_gain_p: [0.5, 0.5, 0.5, 0.5]
    speed_gain_i: [0.2, 0.2, 0.2, 0.2]
    speed_gain_d: [0.0, 0.0, 0.0, 0.0]
    torque_lim: [0.9, 0.9, 0.9, 1.0]
    pos_gain_p: [6.0, 6.0, 6.0, 6.0]
    pos_gain_i: [3.0, 3.0, 3.0, 3.0]
    pos_gain_d: [0.0, 0.0, 0.0, 0.0]
    speed_lim: [20.0, 20.0, 20.0, 10.0]
    # TRQ+SPD+POSをフィードバック
    monitor_reg1: [0x0001000100010000, 0x0001000100010000, 0x0001000100010000, 0x0001000100010000]
    # TRQ+SPD+POS+MOTOR_STATEをフィードバック
    # monitor_reg1: [0x0001000100010002, 0x0001000100010002, 0x0001000100010002, 0x0001000100010002]
    # VESCのフィードバックは無効化
    monitor_reg2: [0, 0, 0, 0]
    monitor_period: 50
# KFS回収後、展開補助後
sabacan_robomasv2_node_id3:
  ros__parameters:
    board_id: 3
    enable_initialize: false
    # motor_number 3だけSESCなので、ゲインを半分にしている
    motor_type: ["C610", "C610", "C610", "C610"]
    control_type: ["POS", "POS", "POS", "POS"]
    speed_gain_p: [0.5, 0.5, 0.5, 0.25]
    speed_gain_i: [0.2, 0.2, 0.2, 0.1]
    speed_gain_d: [0.0, 0.0, 0.0, 0.0]
    torque_lim: [0.9, 0.9, 0.9, 1.0]
    pos_gain_p: [6.0, 6.0, 6.0, 6.0]
    pos_gain_i: [3.0, 3.0, 3.0, 0.0]
    pos_gain_d: [0.0, 0.0, 0.0, 0.0]
    speed_lim: [20.0, 20.0, 20.0, 10.0]
    # TRQ+SPD+POSをフィードバック
    monitor_reg1: [0x0001000100010000, 0x0001000100010000, 0x0001000100010000, 0x0001000100010000]
    # TRQ+SPD+POS+MOTOR_STATEをフィードバック
    # monitor_reg1: [0x0001000100010002, 0x0001000100010002, 0x0001000100010002, 0x0001000100010002]
    # VESCのフィードバックは無効化
    monitor_reg2: [0, 0, 0, 0]
    monitor_period: 50
# ポール回収
sabacan_robomasv2_node_id4:
  ros__parameters:
    board_id: 4
    enable_initialize: false
    motor_type: ["C610", "C610", "C610", "C610"]
    control_type: ["POS", "POS", "POS", "POS"]
    speed_gain_p: [0.5, 0.5, 0.5, 0.5]
    speed_gain_i: [0.2, 0.2, 0.2, 0.2]
    speed_gain_d: [0.0, 0.0, 0.0, 0.0]
    torque_lim: [1.0, 1.0, 1.0, 1.0]
    pos_gain_p: [6.0, 6.0, 6.0, 6.0]
    pos_gain_i: [3.0, 3.0, 3.0, 3.0]
    pos_gain_d: [0.0, 0.0, 0.0, 0.0]
    speed_lim: [20.0, 20.0, 10.0, 10.0]
    # TRQ+SPD+POSをフィードバック
    monitor_reg1: [0x0001000100010000, 0x0001000100010000, 0x0001000100010000, 0x0001000100010000]
    # TRQ+SPD+POS+MOTOR_STATEをフィードバック
    # monitor_reg1: [0x0001000100010002, 0x0001000100010002, 0x0001000100010002, 0x0001000100010002]
    # VESCのフィードバックは無効化
    monitor_reg2: [0, 0, 0, 0]
    monitor_period: 100
# やり
sabacan_robomasv2_node_id5:
  ros__parameters:
    board_id: 5
    enable_initialize: false
    motor_type: ["C610", "C610", "C610", "C610"]
    control_type: ["POS", "POS", "POS", "POS"]
    speed_gain_p: [0.5, 0.5, 0.5, 0.5]
    speed_gain_i: [0.2, 0.2, 0.2, 0.2]
    speed_gain_d: [0.0, 0.0, 0.0, 0.0]
    torque_lim: [1.0, 1.0, 1.0, 0.7]
    pos_gain_p: [6.0, 6.0, 6.0, 6.0]
    pos_gain_i: [3.0, 3.0, 3.0, 0.0]
    pos_gain_d: [0.0, 0.0, 0.0, 0.0]
    speed_lim: [10.0, 10.0, 15.0, 10.0]
    # TRQ+SPD+POSをフィードバック
    monitor_reg1: [0x0001000100010000, 0x0001000100010000, 0x0001000100010000, 0x0001000100010000]
    # TRQ+SPD+POS+MOTOR_STATEをフィードバック
    # monitor_reg1: [0x0001000100010002, 0x0001000100010002, 0x0001000100010002, 0x0001000100010002]
    # VESCのフィードバックは無効化
    monitor_reg2: [0, 0, 0, 0]
    monitor_period: 100
# R2昇降
sabacan_robomasv2_node_id6:
  ros__parameters:
    board_id: 6
    enable_initialize: false
    motor_type: ["C620", "C610", "C610", "C610"]
    control_type: ["VELOCITY", "POS", "POS", "POS"]
    speed_gain_p: [0.5, 0.5, 0.5, 0.5]
    speed_gain_i: [0.2, 0.2, 0.2, 0.2]
    speed_gain_d: [0.0, 0.0, 0.0, 0.0]
    torque_lim: [5.5, 1.0, 1.0, 0.5]
    pos_gain_p: [6.0, 6.0, 6.0, 6.0]
    pos_gain_i: [3.0, 3.0, 3.0, 3.0]
    pos_gain_d: [0.0, 0.0, 0.0, 0.0]
    speed_lim: [50.0, 10.0, 10.0, 10.0]
    # TRQ+SPD+POSをフィードバック
    monitor_reg1: [0x0001000100010000, 0x0, 0x0, 0x0]
    # TRQ+SPD+POS+MOTOR_STATEをフィードバック
    # monitor_reg1: [0x0001000100010002, 0x0001000100010002, 0x0001000100010002, 0x0001000100010002]
    # VESCのフィードバックは無効化
    monitor_reg2: [0, 0, 0, 0]
    monitor_period: 100
# PWM出力
sabacan_gpio_node_id1:
  ros__parameters:
    board_id: 1
    enable_initialize: false
    pin_type: ["OUTPUT_PWM", "OUTPUT_PWM", "OUTPUT_PWM", "OUTPUT_PWM", "OUTPUT_PWM", "OUTPUT_PWM", "OUTPUT_PWM", "OUTPUT_PWM", "OUTPUT_PWM"]
    pwm_freq: [1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000]
    # monitor_regは無効
    monitor_reg: 0
    monitor_period: 0
# センサー入力
sabacan_gpio_node_id2:
  ros__parameters:
    board_id: 2
    enable_initialize: false
    pin_type: ["INPUT", "INPUT", "INPUT", "INPUT", "INPUT", "INPUT", "INPUT", "OUTPUT_PWM", "OUTPUT_PWM"]
    pwm_freq: [0, 0, 0, 0, 0, 0, 0, 1000, 1000]
    # monitor_regはPORT_READを有効化
    monitor_reg: 0x4
    monitor_period: 50
# ポール用
sabacan_gpio_node_id3:
  ros__parameters:
    board_id: 3
    enable_initialize: false
    # 0~3はサーボ、4~7は電磁弁
    pin_type: ["OUTPUT_SERVO", "OUTPUT_SERVO", "OUTPUT_SERVO", "OUTPUT_SERVO", "OUTPUT_PWM", "OUTPUT_PWM", "OUTPUT_PWM", "OUTPUT_PWM", "OUTPUT_PWM"]
    pwm_freq: [0, 0, 0, 0, 1000, 1000, 1000, 1000, 1000]
    servo_max_angle: [270, 270, 270, 270, 270, 270, 270, 270, 270]
    # monitor_regは無効
    monitor_reg: 0
    monitor_period: 0

sabacan_power_node_id0:
  ros__parameters:
    board_id: 0
    enable_initialize: false
    monitor_period: 100

sabacan_led_node_id1:
  ros__parameters:
    board_id: 1
    enable_initialize: false
